# Generated by Django 4.2.3 on 2023-08-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_cart_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='avialable',
            field=models.BooleanField(default=True),
        ),
    ]
