# Generated by Django 4.2.4 on 2023-08-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_avialable_product_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_edit_products', 'Can edit products')]},
        ),
    ]
