# Generated by Django 4.2.4 on 2023-08-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_resetpassword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_edit_users', 'Can edit users')]},
        ),
    ]
