# Generated by Django 4.2.3 on 2023-08-12 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paypal', '0002_alter_paypalorder_cart_alter_paypalorder_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_cart_items', to='paypal.archivecart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_cart_items', to='paypal.archiveproduct')),
            ],
        ),
        migrations.AddField(
            model_name='archivecart',
            name='products',
            field=models.ManyToManyField(related_name='archive_carts', through='paypal.ArchiveCartItem', to='paypal.archiveproduct'),
        ),
    ]
