# Generated by Django 4.2.3 on 2023-08-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0003_archivecart_archiveproduct_archivecartitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivecartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='archivecartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='ArchiveCart',
        ),
        migrations.DeleteModel(
            name='ArchiveCartItem',
        ),
        migrations.DeleteModel(
            name='ArchiveProduct',
        ),
    ]
